
replicaCount: 1
name:
  my-app
service:
  type: ClusterIP
  port: 80
  name: my-service

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 50m
     memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http


