
replicaCount: 2

service:
  type: ClusterIP
  port: 80

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 70m
     memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

